### ISSUE TITLE
Question: App Name and App Roles

### ISSUE THREAD

**Issue by oitTim** [nais/azurerator#283]
Is it possible to change the Azure app name to something besides "clustername:namespace:metadata.name"?  Our authenticator app shows the Azure application Display Name the user is authenticating to and we prefer it to show "MyApp" instead of "some-cluster:some-namespace:MyApp"

Also, I noticed Azureator creates two appRoles inside of Azure.  Is it possible that we can add more custom appRoles of our own?  Could you tie that back to claims: groups: Something like:

```yaml
claims:
    groups:
      - id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"  
        approle: "app role A"

appRoles:
   -  displayName: "app role A"
      allowedMemberTypes:
        - User/Group
      description: "some description"
      isEnabled: true
      value: "value to pass to claims"
 ```

I have a feeling these would have to become feature requests?  I did not see any immediate documentation referring to these capabilities.

**Comment by tronghn** [comment]
Unfortunately, Azurerator uses this specific naming format for lookups in Azure AD. We generally pre-approve permissions for our application, which means end-users are usually never prompted for permissions when logging in (as these are internal applications that we trust). 

The naming format is also related to the `.spec.preAuthorizedApplications` stanza that grants appRoles and permissionScopes to consumer applications where you can grant access to consumer applications:

```yaml
spec:
  preAuthorizedApplications:
    - application: some-consumer-api
      namespace: some-namespace
      cluster: some-cluster
```

This grants the matching application the default AppRole and PermissionScope that Azurerator also creates.
Additional customroles and scopes can also be created and assigned to consumers in a similar mannner:

```yaml
spec:
  preAuthorizedApplications:
    - ...
      roles:
        - some-role
      scopes:
        - some-scope
```

A group can be assigned to the application's default approle through the `.spec.claims` stanza:

```yaml
spec:
  claims:
    groups:
      - id: <object id of Azure group>
```

This emits the object ID of the group to the `groups` claim in the user's token, if they're a direct member of said group.

Unfortunately, we do not support assigning groups (nor users) to specific approles at this time, and currently have no capacity to do so due to other priorities.
